// =============================================================
//  DADOS DA EXPOSIÇÃO — totalmente editáveis
//  Para alterar uma obra, edite os campos de texto abaixo.
//  Para trocar uma imagem, substitua a "src" pelo novo endereço.
// =============================================================

const artworks = [
  {
    id: 'tekoha',
    title: 'Tekoha',
    inspiration: 'Inspirada em Ziel Karapotó',
    turma: '1º AUT-T1 (Grupo 3)',
    year: '2026',
    authors: 'Davi dos Santos Francisco, Helcio Raphael Gomes, João Vitor Suares, Miguel Benício Costa, Nícolas de Jesus Pereira, Pablo Henrique Rodrigues, Rafael Henrique, Riquelme Henrique, Ronald Alves Lopes, Victória Eduarda Gomes, Victoria Eduarda Martins, Walak Junio, Yago de Souza Silva',
    description: [
      'Nossa instalação foi inspirada na obra "Cardume" de Ziel Karapotó, que tem como objetivo gerar a reflexão acerca das diferenças entre variados grupos indígenas e a influência dos colonizadores na história do Brasil, incluindo o impacto da exploração dos povos originários. A imagem do cardume simboliza a união, a coletividade e a resistência dos povos indígenas, que continuam lutando pela preservação de suas identidades, tradições, territórios e modos de vida.',
      'O nome da nossa instalação, Tekoha, vem de um termo de origem Guarani que se traduz literalmente como "o lugar onde se dá o modo de ser". Ao abordar a resistência indígena contra o garimpo ilegal, a instalação evidencia a luta pela proteção do Tekoha, ameaçado pela degradação ambiental e pela invasão de terras. Usamos a bateia como representação do garimpo ilegal e o "sangue" expressando os custos desse garimpo para o povo indígena — considerando a simbologia em que a terra é um ser vivo, não apenas recurso.',
      'Em contrapartida, as penas e as pedras funcionam como representativos de esperança e resistência, associando-se aos próprios elementos da cultura indígena e da natureza. As pedras formam um símbolo Guarani de união e resistência, traçando um paralelo com os temas abordados e com os elementos da obra de Ziel Karapotó.',
    ],
    images: [
      { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/20260612_135502-ztYBfrIlwBINBulwCustYpD0XtpvSU.jpg', alt: 'Pena branca em primeiro plano com a bateia repleta de terra avermelhada ao fundo.' },
      { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/20260612_135423-P58u1HIsXuLK86Zld8ezEzupgPBT6Y.jpg', alt: 'Bateia circular cheia de terra avermelhada com um desenho radial em tom de sangue.' },
      { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/20260612_135408-yXQddZKRZtTHAL4OltoPdWcyp2UNTl.jpg', alt: 'Pedras cinza-azuladas dispostas na terra formando padrões e manchadas de vermelho.' },
      { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/20260612_135433-19mK1s2exvK2i4stc7PsbfChlEvnL1.jpg', alt: 'Pedras claras sobre a areia formando padrões com sangue, ao lado da borda da bateia.' },
      { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/20260612_135357-ZZwLLbzhyNGhsY5FRyP4U3wsKczymk.jpg', alt: 'Placa da obra Tekoha fixada no solo do campus.' },
    ],
    video: 'https://drive.google.com/file/d/1slBcfg7c39VZ9Ti_VCMDcO0QQbjhGD6q/view?usp=sharing',
  },
  {
    id: 'entre-o-silencio-das-folhas',
    title: 'Entre o Silêncio das Folhas',
    inspiration: 'Inspirada em Olinda Tupinambá',
    turma: '1º AUT-T2',
    year: '2026',
    authors: 'Ana Júlia, André, Carlos, Emilly, Filipe, Jhenifer, Lavínia, Lucca, Maísa, Otávio, Pedro e Samuel.',
    description: [
      'Nossa instalação foi inspirada na obra Ibirapema, de Olinda Tupinambá, artista que aborda em sua produção temas ligados à ancestralidade, à natureza, à resistência dos povos originários e às marcas deixadas pelas transformações do território. Criamos uma obra que convida o público a atravessar um espaço de reflexão sobre a destruição ambiental e seus impactos sobre a vida, a cultura e a memória.',
      'A instalação ocupa um corredor extremamente estreito, onde diversos elementos naturais ficam suspensos acima da cabeça do visitante. A sensação de passagem é acompanhada por uma ideia de aperto e sufocamento, simbolizando a pressão exercida sobre as florestas e sobre os povos que dependem delas para sobreviver, diante do avanço constante da destruição ambiental.',
      'As folhas secas penduradas representam a morte das florestas. As penas simbolizam a fauna atingida pela destruição dos ecossistemas e a forte ligação entre os povos indígenas e os elementos naturais. As miçangas representam os vínculos entre natureza, memória e cultura — saberes transmitidos entre gerações e a continuidade da vida.',
    ],
    images: [
      { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/20260612_084825-29ZXJybEQgDI6HKDupHIge7uNb6vEF.jpg', alt: 'Corredor estreito ao ar livre com folhas secas, penas e miçangas penduradas entre as paredes.' },
      { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/20260612_084841-kv8lTXANUI078xS418BnmMO7ZGBHnz.jpg', alt: 'Vista para cima de um corredor estreito entre prédios, com fios, penas e plantas secas suspensos.' },
      { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/20260612_084913-jiJlcOEQlmykZ5RLxxOmzwSh2itDrt.jpg', alt: 'Cachos de grãos secos pendurados no corredor estreito.' },
      { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/20260612_084734-B2Mt960QbpTqwdiuNPgLwlbuWvWIh1.jpg', alt: 'Cordão de miçangas coloridas e folhas secas pendurados em um cano.' },
      { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/20260612_084717-i6K5zUINZzFKRG6jHQWuPwx0qTwF3h.jpg', alt: 'Pena vermelha presa por um cordão, pendurada contra uma parede branca.' },
    ],
  },
  {
    id: 'a-pele-ancestral-enclausurada',
    title: 'A Pele Ancestral Enclausurada',
    inspiration: 'Inspirada em Glicéria Tupinambá',
    turma: '1º ano MEC-T1',
    year: '2026',
    authors: 'Adler, Ana Júlia, Beatriz, Gustavo, Gustavo Sathler, João Antônio, Lucas Cardoso, Maria Eduarda, Mariano, Quetsia, Sarah e Thales.',
    description: [
      'Nossa instalação foi inspirada na obra de Glicéria Tupinambá, que tem como crítica a apropriação europeia dos mantos sagrados da tribo Tupinambá. Em alusão a isso, a nossa instalação coloca um cocar indígena posicionado acima de uma coroa europeia, invertendo a lógica de poder e colocando a cultura indígena em destaque. Tudo está sobre a grama, em um pedestal cercado por pedras — representando um museu indígena que inverte a atual realidade da apropriação cultural e do sequestro dos mantos Tupinambás.',
      'Com isso, queremos provocar três questões: quem detém o poder de contar a história, de quem é o patrimônio cultural e como reparar a colonização. A instalação eleva o cocar indígena para discutir a devolução, o respeito e o protagonismo dos povos originários na arte.',
      'A escolha dos materiais naturais, tendo as penas como um dos materiais principais, dialoga com a obra de Glicéria Tupinambá, para quem o manto é "um ente vivo" que conecta corpo e território. Ao usar as penas como material central, reafirmamos que corpo, território e cultura são indissociáveis.',
    ],
    images: [
      { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/20260610_083440-9UAMgXQONDlcJeHUe5IB4IGIYbVQDd.jpg', alt: 'Coroa dourada com pérolas e penas sobre uma base trançada, em um jardim.' },
      { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/20260610_083603-wWuvXDgtzN5QIWQ5qAAZPqDjAqSyhj.jpg', alt: 'Vista de cima do cocar de penas sobre o chão, cercado por pedras dispostas em círculo.' },
    ],
  },
  {
    id: 'o-vazio',
    title: 'O Vazio',
    inspiration: 'Inspirada em Glicéria Tupinambá',
    turma: '1º AUT-T2',
    year: '2026',
    authors: 'Alicia Matos, Ana Luiza Paiva, Bernardo Rocha, Cauã Wilian, Felipe Rezende, Gabriela Regina, João Paulo, Keterson Christian, Larissa Fernanda, Lucas Machado, Marcos Daniel, Richard Oliveira, Victor Schuffner.',
    description: [
      'A nossa instalação foi inspirada na obra de Glicéria Tupinambá e seu objetivo é provocar no público o sentimento de um vazio deixado na cultura tupinambá pelo roubo de seus mantos, discutindo a luta indígena pela preservação de sua cultura. Foram utilizados 14 armários da escola, sendo 11 deles vazios, representando os mantos roubados e levados para a Europa.',
      'Nos outros 3 armários é possível notar um tecido vermelho remendado, representando o manto Tupinambá recuperado; folhas secas dentro de um deles e penas vermelhas no outro. Esses elementos transmitem ao espectador um sentimento de ausência pelos mantos que foram roubados e não foram completamente devolvidos ao Brasil até hoje.',
      'Escolhemos utilizar armários porque são objetos destinados a guardar e preservar aquilo que possui valor, simbolizando a memória e a cultura tupinambá. Ao representá-los vazios, mostramos a ausência causada pela remoção dos mantos, que permanecem em museus europeus, distantes do povo ao qual pertencem.',
    ],
    images: [
      { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/20260612_083827-S4zNoe4GPBgh5fxuYnGz4y5LVfyZ4o.jpg', alt: 'Penas vermelhas acumuladas dentro de um armário cinza da escola.' },
      { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/20260612_083945-G5UvWjUHMLk1zLpARhJiuO4qwBs78x.jpg', alt: 'Folhas secas acumuladas dentro de um armário cinza.' },
      { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/20260612_083928-lwuN92TG9NsuCIgP2ai11jd6VcbjMJ.jpg', alt: 'Folhas secas douradas presas nas frestas de ventilação de um armário cinza.' },
      { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/20260612_083843-Chnk89CytWYhus1QZcGzv6C3YmPIve.jpg', alt: 'Close-up de penas vermelhas sobrepostas.' },
      { src: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/20260612_083919-oYxKwQCjNU3JXq2boUKn3TtaLsuyPA.jpg', alt: 'Penas vermelhas e naturais espalhadas sobre um fundo escuro.' },
    ],
  },
  {
    id: 'resistir-para-existir',
    title: 'Resistir para Existir',
    inspiration: 'Inspirada em Ziel Karapotó',
    turma: '1º Automação Industrial - T2',
    year: '2026',
    authors: 'Ana Luiza, Artur, Emanuelle, Gustavo, João Augusto, João Victor, Karen, Laís, Letícia, Luís Fernando, Sarah, Sabrina, Marcos Henrique.',
    description: [
      'Nossa instalação foi inspirada na obra de Ziel Karapotó, artista indígena que busca os direitos de seu povo, como o território — que, além de ser um espaço físico, também representa um espaço cultural e religioso. O objetivo da obra é representar como os direitos direcionados aos povos indígenas acabam sendo esquecidos e como eles buscam trazer isso de volta.',
      'Utilizamos uma estátua da "Justiça Cega" derrubada ao lado de um pedestal tombado, cordas presas no pedestal e na árvore para representar a luta destes povos por seus direitos, uma corda com a ponta solta — trazendo a ideia de que falta algo — além de vasos de cerâmica, um deles quebrado, representando a negação à colonização e a rejeição à imposição da cultura europeia.',
      'A disposição dos elementos busca provocar no público uma conscientização sobre a importância da sua participação na luta por leis e direitos políticos dos povos originários, dialogando com a busca do artista por maior reconhecimento cultural.',
    ],
    images: [
      { src: 'obras/resistir-para-existir/01-vista-geral.png', alt: 'Vista geral da instalação Resistir para Existir: pedestal de concreto tombado, corda, vasos de cerâmica e estátua da Justiça Cega.' },
      { src: 'obras/resistir-para-existir/02-pedestal-tombado.png', alt: 'Pedestal de concreto caído amarrado com corda amarela e preta, com a estátua dourada da Justiça Cega no chão.' },
      { src: 'obras/resistir-para-existir/03-pedestal-e-arvore.png', alt: 'Pedestal amarrado com corda diante de árvore envolta por fios vermelhos e tecido estampado.' },
      { src: 'obras/resistir-para-existir/04-encosta-corda-vasos.png', alt: 'Instalação na encosta do campus: pedestal, corda, vasos de cerâmica e estátua dourada sobre a terra.' },
      { src: 'obras/resistir-para-existir/05-vaso-e-cacos.png', alt: 'Vaso de cerâmica intacto entre fragmentos quebrados, com pedestal e corda ao fundo.' },
      { src: 'obras/resistir-para-existir/06-terracota-quebrada.png', alt: 'Vaso de terracota em pé cercado por cacos de cerâmica espalhados sobre o solo seco.' },
      { src: 'obras/resistir-para-existir/07-justica-caida-balanca.png', alt: 'Close-up da estátua dourada da Justiça Cega caída sobre a terra, segurando a balança.' },
      { src: 'obras/resistir-para-existir/08-justica-caida-solo.png', alt: 'Estátua dourada da Justiça Cega tombada no solo entre pedras e capim seco.' },
    ],
    video: 'https://drive.google.com/file/d/1zbrVtSwBcW7HW8kHc3_CU3IXA2xYJMFi/view?usp=sharing',
  },
  {
    id: 'a-dor-da-origem',
    title: 'A Dor da Origem',
    inspiration: 'Inspirada em Ziel Karapotó',
    turma: '1º Química - T2',
    year: '2026',
    authors: 'Arthur, Davi, Ester, Hellen, Laura Gonçalves, Mariah, Maria Alice, Mariana, Rafaela, Wendy, Giovanna.',
    description: [
      'A instalação inspira-se na poética de Ziel Karapotó, que utiliza a arte e os saberes ancestrais como ferramentas de resistência. O grupo reinterpretou as marcas, as cores terrosas e a valorização da natureza e dos sentidos, relacionando esses elementos ao tema da memória, identidade e resistência indígena.',
      'Disposta no barranco atrás do laboratório, a obra integra a própria natureza local como parte de sua narrativa. O tecido branco representa a memória, a ancestralidade e a presença dos povos originários; sobre ele, marcas de tinta em tons terrosos representam folhas e terra, enquanto impressões de mãos simbolizam as marcas deixadas pela história.',
      'Os barbantes vermelhos entrelaçados entre as árvores criam uma barreira que representa as dificuldades de acesso à verdadeira história indígena. A experiência sonora, composta por ruídos, gritos e sons de queimadas, busca provocar desconforto e reflexão sobre a perda de territórios e a destruição ambiental.',
    ],
    images: [
      { src: 'obras/a-dor-da-origem/01-vista-geral.png', alt: 'Vista geral da instalação A Dor da Origem.' },
      { src: 'obras/a-dor-da-origem/02-banner-barranco.png', alt: 'Banner com o texto "A Dor da Origem" na cor branca sobre um fundo vermelho.' },
      { src: 'obras/a-dor-da-origem/03-tecido-e-arvore.png', alt: 'Tecido branco estampado entre árvores.' },
      { src: 'obras/a-dor-da-origem/04-fios-entre-arvores.png', alt: 'Fios vermelhos entrelaçados entre árvores.' },
      { src: 'obras/a-dor-da-origem/05-detalhe-maos-fios.png', alt: 'Detalhe de mãos impressas no fio vermelho.' },
      { src: 'obras/a-dor-da-origem/06-detalhe-impressoes.png', alt: 'Detalhe de impressões de mãos no tecido branco.' },
      { src: 'obras/a-dor-da-origem/07-detalhe-barbantes.png', alt: 'Detalhe de barbantes vermelhos entrelaçados entre árvores.' },
      { src: 'obras/a-dor-da-origem/08-detalhe-maos-folhas.png', alt: 'Detalhes de impressões de mãos e folhas no tecido branco.' },
    ],
    video: 'https://drive.google.com/file/d/1EiP-HzBKokY2yDwtgoEAIEfKm72MpX3Y/view?usp=sharing',
  },
  {
    id: 'reflexo-colonial',
    title: 'Reflexo Colonial',
    inspiration: 'Inspirada em Ziel Karapotó',
    turma: '1º ano MEC-T1',
    year: '2026',
    authors: 'Ana Clara Marinho Ribeiro, Daniel Magalhães Nonato, Isis Lorena Cordeiro Silva, João Vitor da Silva Romão, Juan Pablo Jadir Ferreira Magalhães, Laura Pinheiro Mota, Letícia Pereira da Silva, Letícia Rodrigues dos Santos, Liviane Heloísa Oliveira, Lucas Guimarães Vieira, Marcele Nascimento Magalhães, Miguel Fernando Pacidônio Pereira, Sofia Resende Monteiro dos Santos.',
    description: [
      'Nossa instalação foi inspirada na obra de Ziel Karapotó e busca evidenciar o quão violenta foi a chegada dos portugueses ao Brasil, relacionando esse processo ao genocídio e à nossa ancestralidade indígena, que muitas vezes foi e ainda é apagada dos livros de História e da vida dos brasileiros.',
      'Utilizamos tecido azul e tecido vermelho, varas de pesca, caixas de madeira, um espelho, artefatos de uso cotidiano e um cocar para representar a captura e a dominação dos indígenas pelos europeus. A disposição dos elementos pretende provocar no público uma sensação de desconforto pela posição em que ele fica em relação à obra.',
      'Seu principal objetivo é promover uma reflexão sobre o apagamento da ancestralidade indígena na história do Brasil — uma vez que a história do nosso país é frequentemente contada sob a perspectiva europeia, e não pela visão dos povos que já habitavam o território.',
    ],
    images: [
      { src: 'obras/reflexo-colonial/capa.jpg', alt: 'Capa da obra Reflexo Colonial.' },
      { src: 'obras/reflexo-colonial/1.jpg', alt: 'Vista da instalação Reflexo Colonial.' },
      { src: 'obras/reflexo-colonial/2.jpg', alt: 'Vista da instalação Reflexo Colonial.' },
      { src: 'obras/reflexo-colonial/3.jpg', alt: 'Vista da instalação Reflexo Colonial.' },
      { src: 'obras/reflexo-colonial/4.jpg', alt: 'Vista da instalação Reflexo Colonial.' },
      { src: 'obras/reflexo-colonial/5.jpg', alt: 'Vista da instalação Reflexo Colonial.' },
    ],
    video: 'https://drive.google.com/file/d/1eox02Qkn4kcIR6IlMcd3BnsCeWv5O29M/view?usp=sharing',
  },
  {
    id: 'territorio-vivo',
    title: 'Território Vivo',
    inspiration: 'Inspirada em Olinda Tupinambá',
    turma: '1º AUT-T1',
    year: '2026',
    authors: 'Pyetro Calazans, David Natanael, Lucas Gabriel, Enzo Ferreira, Davi Klitzke, Ana Clara, Emmanuel Vitor, Kaick Junio, Nicolas Fernando, Wallace Rodrigues, Gustavo Fernando, Thiago Henrique.',
    description: [
      'Nossa instalação foi inspirada na obra "O Parto", da artista indígena Olinda Tupinambá, e busca discutir a relação entre território, ancestralidade, identidade e existência. A instalação é composta por um caminho formado por diferentes materiais naturais, como terra, grama e areia, que os visitantes percorrem descalços.',
      'No centro da obra há um ninho construído com os mesmos elementos do percurso, simbolizando origem, nascimento e conexão com a terra. Ao retirar os sapatos e caminhar lentamente, o visitante experimenta o território por meio do próprio corpo, percebendo diferentes texturas e sensações.',
      'A terra representa a origem da vida e a conexão ancestral entre os seres humanos e o território. A grama simboliza crescimento, renovação e esperança: mesmo quando é pisada ou cortada, ela volta a crescer, reforçando a ideia de continuidade e a ligação entre os seres humanos e a natureza.',
    ],
    images: [
      { src: 'obras/territorio-vivo/01-capa.jpg', alt: 'Capa da obra Território Vivo.' },
      { src: 'obras/territorio-vivo/02.jpg', alt: 'Vista da instalação Território Vivo.' },
      { src: 'obras/territorio-vivo/03.jpg', alt: 'Vista da instalação Território Vivo.' },
      { src: 'obras/territorio-vivo/04.jpg', alt: 'Vista da instalação Território Vivo.' },
    ],
    video: 'https://drive.google.com/file/d/1JvEIyy6CeuKWBqrXnd5IqtPAGjl5B2ER/view?usp=sharing',
  },
  {
    id: 'terra-preciosa',
    title: 'Terra Preciosa',
    inspiration: 'Inspirada em Olinda Tupinambá',
    turma: '1º Química - T1',
    year: '2026',
    authors: 'Alice Coelho, Arthur Vinícius, Camila, Davi Eduardo, Eloah, Helena Pereira, Letícia Gabrielly, Maria Eduarda Fonseca, Nicole, Sofia Helena.',
    description: [
      'Nossa instalação foi inspirada na obra de Olinda Tupinambá e busca discutir a relação de exploração da terra e o apagamento da história dos povos originários. Utilizamos materiais como pás, a própria terra e fitas de isolamento (cena de crime) para representar visualmente e de forma interativa a violação territorial.',
      'A disposição dos elementos pretende provocar no público uma participação ativa, convidando o espectador a manusear as pás e cavar o solo, gerando uma experiência de reflexão física e sensorial. O buraco cavado remete às terras exploradas ao longo da história.',
      'Enquanto o espectador comum espera encontrar algum minério de valor comercial ao cavar, nossa instalação quer justamente mostrar a preciosidade da própria terra em seu estado natural, denunciando o quão esquecido foi o crime ocorrido nela.',
    ],
    images: [
      { src: 'obras/terra-preciosa/01-capa.jpg', alt: 'Capa da obra Terra Preciosa.' },
      { src: 'obras/terra-preciosa/02.jpg', alt: 'Vista da instalação Terra Preciosa.' },
      { src: 'obras/terra-preciosa/03.jpg', alt: 'Vista da instalação Terra Preciosa.' },
      { src: 'obras/terra-preciosa/04.jpg', alt: 'Vista da instalação Terra Preciosa.' },
      { src: 'obras/terra-preciosa/05.jpg', alt: 'Vista da instalação Terra Preciosa.' },
      { src: 'obras/terra-preciosa/06.jpg', alt: 'Vista da instalação Terra Preciosa.' },
    ],
  },
  {
    id: 'origens-soterradas',
    title: 'Origens Soterradas',
    inspiration: 'Inspirada em Olinda Tupinambá',
    turma: '1º Química - T2',
    year: '2026',
    authors: 'Amanda Lorrayne, Brenda de Castro, Eric Calazans, Flávia Rabelo, Izabelle Fernanda, Júlia Oliveira, Lara Vitória, Luiza Péret, Mariana Santos, Miguel Araújo.',
    description: [
      'Nossa referência para a instalação foi a obra "O Parto" de Olinda Tupinambá. Ela provoca uma reflexão sobre a visão distorcida dos povos originários na sociedade atual, imposta pelos meios de comunicação, evidenciando o quão estereotipada é essa visão.',
      'A instalação consiste em uma árvore com vários fios ligados à terra, com terra mexida em volta, um regador que goteja água vermelha e um telefone sem fio, que vai da terra até a copa da árvore e tem um nó no meio do fio. Os fios enfatizam como as tecnologias sufocam a natureza e os indígenas.',
      'O telefone sem fio com o nó trata da ruptura e da distorção da informação que vem das raízes e chega até nós. O regador representa as pessoas que regam as fake news em nossas raízes, onde, de gota em gota, o que parece inofensivo se torna uma cicatriz em nossa história — representando também o sangue derramado dos povos originários.',
    ],
    images: [
      { src: 'obras/origens-soterradas/01-capa.jpg', alt: 'Capa da obra Origens Soterradas.' },
      { src: 'obras/origens-soterradas/02.jpg', alt: 'Vista da instalação Origens Soterradas.' },
      { src: 'obras/origens-soterradas/03.jpg', alt: 'Vista da instalação Origens Soterradas.' },
      { src: 'obras/origens-soterradas/04.jpg', alt: 'Vista da instalação Origens Soterradas.' },
      { src: 'obras/origens-soterradas/05.jpg', alt: 'Vista da instalação Origens Soterradas.' },
      { src: 'obras/origens-soterradas/06.jpg', alt: 'Vista da instalação Origens Soterradas.' },
      { src: 'obras/origens-soterradas/07.jpg', alt: 'Vista da instalação Origens Soterradas.' },
      { src: 'obras/origens-soterradas/08.jpg', alt: 'Vista da instalação Origens Soterradas.' },
      { src: 'obras/origens-soterradas/09.jpg', alt: 'Vista da instalação Origens Soterradas.' },
      { src: 'obras/origens-soterradas/10.jpg', alt: 'Vista da instalação Origens Soterradas.' },
      { src: 'obras/origens-soterradas/11.jpg', alt: 'Vista da instalação Origens Soterradas.' },
    ],
    video: 'https://drive.google.com/file/d/1V7NR5WTLp3Oun7j22rwY8ePABCzAzZ5Q/view?usp=sharing',
  },
  {
    id: 'o-sagrado-entre-a-natureza-e-o-luxo',
    title: 'O Sagrado entre a Natureza e o Luxo',
    inspiration: 'Inspirada em Glicéria Tupinambá',
    turma: '1º Química - T1',
    year: '2026',
    authors: 'Gabriella Macedo, Davi Henrique, Samuel Vinícius, Júlia Rodrigues, Miguel Ferreira, Vinícius, Ana Luiza, Isabela, Marcela, Maria Eduarda Martins, Letícia, Thiago.',
    description: [
      'Nossa instalação foi inspirada na obra Okará Assojaba, da artista indígena Glicéria Tupinambá, e busca discutir a relação entre o sagrado, a natureza e o luxo, mostrando como elementos naturais e culturais indígenas são retirados de seu contexto original e transformados em objetos de exposição e valor material.',
      'Utilizamos uma gaiola que abriga o objeto sagrado central: um manto de penas, rodeado por folhas verdes e orgânicas. A composição tensiona a ideia de aprisionamento e a transformação da herança nativa em um bem tutelado que emula a estrutura de conservação e o luxo dos acervos modernos. Ao redor, cercas estruturais delimitam o território da instalação.',
      'A disposição provoca uma sensação de distanciamento, controle e exclusão: o espectador é impossibilitado de acessar diretamente o manto e as folhas, restando-lhe observá-los através das barreiras. O objetivo é refletir sobre o que acontece quando a natureza e a cultura são retiradas de seu contexto original.',
    ],
    images: [
      { src: 'obras/o-sagrado-entre-a-natureza-e-o-luxo/01-capa.jpg', alt: 'Capa da obra O Sagrado entre a Natureza e o Luxo.' },
      { src: 'obras/o-sagrado-entre-a-natureza-e-o-luxo/02.jpg', alt: 'Vista da instalação O Sagrado entre a Natureza e o Luxo.' },
      { src: 'obras/o-sagrado-entre-a-natureza-e-o-luxo/03.jpg', alt: 'Vista da instalação O Sagrado entre a Natureza e o Luxo.' },
      { src: 'obras/o-sagrado-entre-a-natureza-e-o-luxo/04.jpg', alt: 'Vista da instalação O Sagrado entre a Natureza e o Luxo.' },
      { src: 'obras/o-sagrado-entre-a-natureza-e-o-luxo/05.jpg', alt: 'Vista da instalação O Sagrado entre a Natureza e o Luxo.' },
      { src: 'obras/o-sagrado-entre-a-natureza-e-o-luxo/06.jpg', alt: 'Vista da instalação O Sagrado entre a Natureza e o Luxo.' },
    ],
  },
  {
    id: 'mascaras-da-natureza',
    title: 'Máscaras da Natureza',
    inspiration: 'Inspirada na cultura Tupinambá',
    turma: '1º Automação - T1',
    year: '2026',
    authors: 'Alicia, Bernardo, Lucas Vitor, Victor, Emilly, Raul, Kevin, Gabriel, Davi Passos, Arthur, Nicolas Gabriel, Yara, Pedro.',
    description: [
      '"Máscaras da Natureza" é uma obra inspirada na cultura Tupinambá e composta por 13 máscaras. A máscara principal representa o Pinheiro, enquanto as outras 12 são associadas às árvores próximas ao campus. O número 13 foi escolhido porque a obra foi produzida por 13 pessoas, e cada rosto simboliza deuses e divindades do povo tupinambá.',
      'A máscara principal possui raízes que se conectam à árvore, representando sua ligação com a natureza, que resiste e continua viva. A obra busca causar um leve desconforto: observada de longe, transmite estranheza; ao se aproximar, o observador percebe que nos olhos da figura existem espelhos, criando uma nova interpretação.',
      'Esse recurso representa o mesmo sentimento de estranheza que a natureza poderia sentir ao observar as ações humanas. A obra transmite a ideia de que fazemos parte da natureza como um todo, e não somos superiores a ela, reforçando a importância de reconhecer nossa conexão com o mundo natural e com os saberes ancestrais.',
    ],
    images: [
      { src: 'obras/mascaras-da-natureza/01-capa.jpg', alt: 'Capa da obra Máscaras da Natureza.' },
      { src: 'obras/mascaras-da-natureza/02.jpg', alt: 'Vista da instalação Máscaras da Natureza.' },
      { src: 'obras/mascaras-da-natureza/03.jpg', alt: 'Vista da instalação Máscaras da Natureza.' },
      { src: 'obras/mascaras-da-natureza/04.jpg', alt: 'Vista da instalação Máscaras da Natureza.' },
      { src: 'obras/mascaras-da-natureza/05.jpg', alt: 'Vista da instalação Máscaras da Natureza.' },
      { src: 'obras/mascaras-da-natureza/06.jpg', alt: 'Vista da instalação Máscaras da Natureza.' },
      { src: 'obras/mascaras-da-natureza/07.jpg', alt: 'Vista da instalação Máscaras da Natureza.' },
      { src: 'obras/mascaras-da-natureza/08.jpg', alt: 'Vista da instalação Máscaras da Natureza.' },
      { src: 'obras/mascaras-da-natureza/09.jpg', alt: 'Vista da instalação Máscaras da Natureza.' },
      { src: 'obras/mascaras-da-natureza/10.jpg', alt: 'Vista da instalação Máscaras da Natureza.' },
      { src: 'obras/mascaras-da-natureza/11.jpg', alt: 'Vista da instalação Máscaras da Natureza.' },
      { src: 'obras/mascaras-da-natureza/12.jpg', alt: 'Vista da instalação Máscaras da Natureza.' },
    ],
  },
];
